### ISSUE TITLE
Error: While trying to resolve module `react-native-spotify-remote`

### ISSUE THREAD

**Issue by djwillcaine** [cjam/react-native-spotify-remote#100]
Since a change to package.json introduced in 5cdf417cb8566345b953e8e79b099ab165f32c49 the module crashes when not being run from source with the following error message:

    error: Error: While trying to resolve module `react-native-spotify-remote` from file `C:\dev\Juuke\src\constants.js`, the package `C:\dev\Juuke\node_modules\react-native-spotify-remote\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\dev\Juuke\node_modules\react-native-spotify-remote\src\index`. Indeed, none of these files exist:

Removing [lines 33 and 34](https://github.com/cjam/react-native-spotify-remote/blob/master/package.json#L33-L34) from package.json again fixed the issue for me. I'm not actually 100% certain what either of these lines do, to be honest, so I didn't want to just submit a PR removing them. Obviously they make reference to the src directory though, which isn't present when installing the package through npm/yarn, hence the error.

**Comment by djwillcaine** [comment]
Do they just want changing to `dist/index` instead of `src/index`?

**Comment by reteps** [comment]
Also have this issue.

**Comment by cjam** [comment]
Ah shoot, I introduced that issue.  I'll try and get a fix out soon.

**Comment by cjam** [comment]
I merged this in an published 0.3.5 which should fix this.  Let me know and feel free to close this issue if it's fixed.  Thanks @djwillcaine for the PR.

**Comment by cjam** [comment]
Haven't heard anything back so I'm assuming its fixed.
