### ISSUE TITLE
Skip authentication and use remote only

### ISSUE THREAD

**Issue by reteps** [cjam/react-native-spotify-remote#105]
From the comment inside `connect`:
>       // todo: looks like the android remote handles it's own auth (since it doesn't have a token)
>       // todo: argument.  Can probably improve the experience for those who don't need a token
>       // todo: and just want to connect the remote

Thats me!!

This would allow users to handle the token authentication outside of this library. In my case, I do not want a swap endpoint and instead send tokens directly to spotify through PKCE OAUTH.

**Comment by divyanshu013** [comment]
Hi @cjam, I've a similar usecase but not sure how to use the `connectWithoutAuth` method that was added in the PR? Also didn't find it in docs (or maybe I missed it)
