### ISSUE TITLE
"Socket is not connected"

### ISSUE THREAD

**Issue by totte123** [cjam/react-native-spotify-remote#111]
I get a `[connection] nw_write_request_report [C8] Send failed with error "Socket is not connected"` and `dnssd_clientstub write_all(23) DEFUNCT` after logging in to spotify and returning to my app on iphohne X. Any ideas what im doing wrong? My friend tested it on android and it works.

I also looked at your example project and found this in appdelegate.m witch is missing in my appdelegate. What does it exactly do? My build fails if I put it in my appdelegate.m file.
```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)URL options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options
{
  return [[RNSpotifyRemoteAuth sharedInstance] application:application openURL:URL options:options];
}
```

**Comment by cjam** [comment]
This part of the code is what extracts the token from the callback that spotify makes when you do the Auth using this library.  Why does your build fail?  You may need to update your imports so that RNSpotifyRemoteAuth is available.

**Comment by totte123** [comment]
Thanks for the reply. 
I checked the appdelegat.m and managed to successfully build the app. Now after authorization i get a couple new errors:
**nw_write_request_report [C1] Send failed with error "Socket is not connected"**
**[RNSpotifyRemoteAuth application:openURL:options:] [Line 82] Setting application openURL and options on session manager**
**[RNSpotifyRemoteAuth sessionManager:didFailWithError:] [Line 112] Session Manager Failed**
Any ideas what I'm doing wrong?

**Comment by totte123** [comment]
Thanks for the reply.
I checked the appdelegat.m and managed to successfully build the app. Now after authorization i get a couple new errors:
**nw_write_request_report [C1] Send failed with error "Socket is not connected"**
**[RNSpotifyRemoteAuth application:openURL:options:] [Line 82] Setting application openURL and options on session manager**
**[RNSpotifyRemoteAuth sessionManager:didFailWithError:] [Line 112] Session Manager Failed**
Any ideas what I'm doing wrong?

**Comment by totte123** [comment]
I got it working. Thanks for this plugin!
