### ISSUE TITLE
getContentItemForUri is not implemented in Spotify's Android SDK

### ISSUE THREAD

**Issue by kuabhish** [cjam/react-native-spotify-remote#114]
```
getContentItemForUri is not implemented in Spotify's Android SDK
```

How to handle this?
How should I play the song on android?

**Comment by djwillcaine** [comment]
Could you provide some context? What are using the content item for?

If you're trying to use playItem() then you could just use playUri() instead.

    // instead of this
    const item = remote.getContentItemForUri(ITEM_URI_HERE);
    remote.playItem(item);

    // do this
    remote.playUri(ITEM_URI_HERE);

If you're trying to use playItemWithIndex then you can do something like this:

    remote.playItemWithIndex({uri: ITEM_URI_HERE}, INDEX_HERE)

**Comment by kuabhish** [comment]
@djwillcaine  thanks for this answer.. 

`With this, I can play the song in the notification. `

Let's say I want to play the song in my app, search songs (from Spotify), and control the playback of song from my app.

How can I do all these?

**Comment by kuabhish** [comment]
Can I play song with spotify URI in any other react native song player?

**Comment by djwillcaine** [comment]
@kuabhish you might have to be a bit more specific with what you mean by "control the playback". The docs detail all of the different methods you have available to use. 

If, for example, you wanted to play/pause the track when the user pressed a button, that might look something like this:

```javascript


const Controls = ({isPaused}) => {
  function togglePlayback() {
    if (isPaused) remote.play();
    else remote.pause();
  }
  return (
    <Button title={isPaused ? "Play" : "Pause"} onPress={togglePlayback} />
  )
}
```

**Comment by kuabhish** [comment]
Thanks for this @djwillcaine 

Just one more question.. 

How to not play the music in Notification.. and only in Apps UI
or sometime also in the notification if App is closed.

**Comment by kuabhish** [comment]
Let's say I have a song URI... I want to get the details of that song. Can I do it? (Android)

**Comment by kuabhish** [comment]
I think I will have to call this API .. https://api.spotify.com/v1/tracks/{id}

**Comment by djwillcaine** [comment]
This library makes use of the Spotify Remote SDK, it only allows you to remotely control the playback of Spotify. It is not possible to stream music directly within your app without the notification. Not with this library, or any other. That just isn't something Spotify enable you to do. You can see more info about the Android SDK that this library uses [here](https://developer.spotify.com/documentation/android/).

The API you linked is the Spotify Web API that you can use to get information about a track but that API doesn't allow you to stream music or control a users playback.

There is a [beta web playback API](https://developer.spotify.com/documentation/web-playback-sdk/) that might suit your needs but you'd have to build a progressive web app as opposed to a native mobile app. I wouldn't really recommend using it, to be honest. You're best bet is probably to stick with the app remote SDK used in this library and put up with the notification.

**Comment by kuabhish** [comment]
Thanks, @djwillcaine for your suggesstion. 
I will stick with remote SDK. 

Thanks a lot.
