### ISSUE TITLE
'React/RCTConvert.h' file not found

### ISSUE THREAD

**Issue by johra** [cjam/react-native-spotify-remote#12]
Build fails on 'React/RCTConvert.h' file not found, in RNSpotifyConvert.m
Any ideas on how to get this working from a new project? 

Steps to reproduce:
1. expo init --template bare-minimum
2. Follow your install instructions
3. Build project fails

Any help appreciated!

**Comment by cjam** [comment]
Hmm.. so you ejected from expo?  It sounds like it's not able to find the React headers.  I've added an example project in this repo that might be worth cross-referencing.  You can find it here:

https://github.com/cjam/react-native-spotify-remote/tree/master/example

**Comment by cjam** [comment]
Looks like this is a build dependency issue in your project. I'm fixing this for the Cocoapods install, and will try and add something to the readme.  I can't reproduce this on my projects.  But if you're still having this issue, try adding the React library as a dependency in the RNSpotifyRemote library in your xcode project.
