### ISSUE TITLE
ReferenceError: Can't find variable ContentType

### ISSUE THREAD

**Issue by denis0324** [cjam/react-native-spotify-remote#127]
react-native-spotify-remote version: 0.3.6
platform: ios & android

My project is a Javascript project (I mean not a Typescript one)

When I run the project, I am getting this issue. (node_modules/react-native-spotify-remote/src/index.ts)
```
ReferenceError: Can't find variable ContentType
```

**Comment by cjam** [comment]
hey, shoot I must have broken this in the recent release.  I will fix ASAP.

**Comment by cjam** [comment]
Ok @denis0324 can you try v0.3.7?

**Comment by denis0324** [comment]
Hey, @cjam 
Okay, 
Please let me try it today.
And I'll let you know the result asap.
Really Thanks.

**Comment by cjam** [comment]
@denis0324 I'm going to close this, as I assume it has been fixed.
