### ISSUE TITLE
Control volume

### ISSUE THREAD

**Issue by johra** [cjam/react-native-spotify-remote#13]
Is it possible to control the volume somehow? Send event? Or does this have to go through web sdk? https://developer.spotify.com/documentation/web-api/reference/player/set-volume-for-users-playback/

I would really like to do a fade instead of hard cut/pause

**Comment by cjam** [comment]
I couldn't agree more, this would need to be supported by the Spotify iOS SDK.  There's an issue open for it here: https://github.com/spotify/ios-sdk/issues/32

**Comment by cjam** [comment]
Looks like they don't plan to implement this in the remote sdk.

https://github.com/spotify/ios-sdk/issues/32#issuecomment-535856155
