### ISSUE TITLE
com.spotify.sdk.login error 3[IOS]

### ISSUE THREAD

**Issue by srfaytkn** [cjam/react-native-spotify-remote#132]
when i call 'SpotifyAuth.authorize(spotifyConfig);' throws this error:

[Error: The operation couldn’t be completed. (com.spotify.sdk.login error 3.)
The data couldn’t be read because it isn’t in the correct format.]

**Comment by RamonAcedoM** [comment]
Hi, @srfaytkn Are you using the example server for token swap / refresh? I've seen that happen whenever my server was not returning the correct values.

**Comment by srfaytkn** [comment]
The reason why example server returned an error is  that the "encSecret" was undefined ( caused by i didn't set that value) Since i have setted the variable now, problem solved. Thanks a lot for your help

**Comment by himanshuchugh1999** [comment]
hello @srfaytkn can you tell what value did you put in your encsecret because we are facing same error in this while playing the song
