### ISSUE TITLE
Android Calling SpotifyRemote.getPlayerState after SpotifyRemote.playUri throws error

### ISSUE THREAD

**Issue by P-Russell** [cjam/react-native-spotify-remote#144]
Doing this
```js
SpotifyRemote.playUri('some spotify uri')
const playerState = SpotifyRemote.getPlayerState()
```

throws
`
[Error: Attempt to read from field 'long com.spotify.protocol.types.Track.duration' on a null object reference]
`

If I wait one second before calling getState the request resolves successfully.

**Comment by cjam** [comment]
Sorry for the delayed response, not sure why I don't get emails for these.

This library exposes promises for most operations that need to be awaited.  So in your case you should use `async`/`await` or the promise interface:

```ts
// Async await
async function doStuff(){
   await SpotifyRemote.playUri('some spotify uri')
   const playerState = await SpotifyRemote.getPlayerState()
}
// Promises
function doOtherStuff(){
  SpotifyRemote.playUri('some spotify uri').then(()=>{
    return SpotifyRemote.getPlayerState()
 }).then((playerState)=>{ 
 // use playerState
});
}
```

**Comment by cjam** [comment]
Cleaning up old issues, can reopen if needed.
