### ISSUE TITLE
Package does not work with react native unimodules

### ISSUE THREAD

**Issue by XXJJXJ** [cjam/react-native-spotify-remote#145]
I have a project that uses this package to play music from my spotify app. It was working perfectly until I installed react native unimodules and made configurations according to the [official website](https://docs.expo.io/bare/installing-unimodules/) for android, and then my app couldn't detect my spotify app anymore, giving me error:  `Spotify connection failed: could not find the Spotify app, it may need to be installed.` on my console. When I uninstalled it and revert the changes, it works perfectly fine again. Pls advice.

**Comment by cjam** [comment]
hmm.. I'm not sure exactly why that would be happening.  Perhaps it has to do with the check that is being used for whether or not spotify can be called from the current app.  The error you're receiving is from the spotify library itself, not from this library.  I'd have to look at the modifications for the UniModules to see what might be causing it, but I unfortunately am pretty busy with work at the moment.

**Comment by cjam** [comment]
@XXJJXJ did you ever figure out a workaround for this?

**Comment by XXJJXJ** [comment]
Hi there, yeap! Probably not a long term solution, but our project downgraded the version of react-native unimodules to make it work on SDK version 29, then everything worked fine

**Comment by cjam** [comment]
Ok, I'm going to close this issue just to cleanup the backlog.
