### ISSUE TITLE
tokenSwapURL does not work

### ISSUE THREAD

**Issue by nob3110** [cjam/react-native-spotify-remote#147]
I created the endpoints for Token Swap according to the [server readme](https://github.com/cjam/react-native-spotify-remote/blob/master/example-server/README.md).
And I rewrote the url of the source code config.
``` js
import Config from 'react-native-config'
const clientId = Config.SPOTIFY_CLIENT_ID
const spotifyAuthConfig: ApiConfig = {
  clientID: clientId,
  redirectURL: 'com.myapp://oauth',
  tokenRefreshURL: 'https://my-endpoint.com/refresh',
  tokenSwapURL: 'https://my-endpoint.com/swap',
  scopes: [
    ApiScope.StreamingScope,
    ApiScope.AppRemoteControlScope,
    ApiScope.UserReadPlaybackStateScope,
  ],
}
```

However, it seems that it is actually connecting to Spotify Production API without accessing tokenSwapURL.
No logs remain on the my server.

I intentionally put in the URL of Google so that an error will occur, but everything works fine. 
It gets new access token log and beautiful classical music playback.

This is strange...🤔
I tested on Android.

Am I doing something wrong?

```js
import React from 'react'
import {Text} from 'react-native'
import {
  auth as SpotifyAuth,
  remote as SpotifyRemote,
  ApiConfig,
  ApiScope,
} from 'react-native-spotify-remote'

import Config from 'react-native-config'
const clientId = Config.SPOTIFY_CLIENT_ID
const spotifyAuthConfig: ApiConfig = {
  clientID: clientId,
  redirectURL: 'com.myapp://oauth',
  tokenRefreshURL: 'https://google.com',
  tokenSwapURL: 'https://google.com',
  scopes: [
    ApiScope.StreamingScope,
    ApiScope.AppRemoteControlScope,
    ApiScope.UserReadPlaybackStateScope,
  ],
}

export const Debug = () => {
  const debug = React.useCallback( async() => {
    try{
      const session = await SpotifyAuth.authorize(spotifyAuthConfig);
      console.log(session.accessToken) // It outputs like: `BQAMWPUZPSXT-************-OB7orIg`
      await SpotifyRemote.connect(session.accessToken);
      await SpotifyRemote.playUri("spotify:track:6IA8E2Q5ttcpbuahIejO74");
    }catch(err){
      console.error("Couldn't authorize with or connect to Spotify",err);
    }   
  },[])
  React.useEffect(() => {
    debug()
  }, [])
  return (
    <Text>DEBUG PAGE</Text>
  )
}
```

**Comment by nob3110** [comment]
"react": "17.0.1",
"react-native": "0.63.4",
"react-native-config": "^1.4.2",
"react-native-spotify-remote": "^0.3.9",

**Comment by cjam** [comment]
Hm... that is very strange indeed.  Is this only on android or also on iOS?

**Comment by nob3110** [comment]
> Hm... that is very strange indeed. Is this only on android or also on iOS?
No...
It doesn't happen on iOS. Only on Android.

When I authorize with iOS simulator, the server does output the logs. 
If set up unavailable urls (tokenSwapURL and tokenRefreshUrl) like Google.com, it won't be authenticated. 
This seems to be the correct behavior.

I haven't tried it on my physical device yet.

**Comment by cjam** [comment]
This library leverages the integrated Auth flow provided by the Spotify App on the phone.  The Spotify App turns around and hits your configured server and returns back to the calling app on success.  Please try this on a physical device with Spotify installed as the simulator environment is not supported at this time.

**Comment by nob3110** [comment]
Yeah, of course I understand that I need the Spotify app.
So I used a Play Store compatible AVD to install the Spotify app on the emulator. 
Is this method unsupported?

Also test on physical devices. Will report the results soon.

**Comment by cjam** [comment]
@nob3110 great just checking, I've had some people report issues trying to use the simulator.  I haven't tried the Play Store Compatible AVD before, but in theory, it seems like it should work fine.  Let me know how it goes with the devices.

**Comment by nob3110** [comment]
@cjam 
Tested on a physical device.
The result is the same as the emulator test.

Android doesn't connect to my server, it behaves like it connects to Spotify's production server.
iOS successfully connects to my server and it outputs logs.

I do not know the cause. 🤔
I'm testing with the very simple code I posted at the beginning.

Does this happen only in my environment?

**Comment by divyanshu013** [comment]
Can confirm this is happening in my case as well (using real android device). Calling authorize directly retrieves the token from spotify API without hitting backend server that I've configured in token refresh / swap URLs. I was wondering if I need to build the logic for refreshing token manually in my case.

Can't test on iOS so not sure about iOS.

**Comment by cjam** [comment]
Hey @divyanshu013 & @nob3110,

Sorry I gave you a crappy answer earlier in this thread.  I forgot, but have since remembered that the authFlow for iOS and Android are performed differently.  For iOS, it uses the token URL's provided in the config and will hit your server to get the tokens.  On android however, the auth library simply uses the app on the phone and scoops the current session returning a token (described [here](https://developer.spotify.com/documentation/android/guides/android-authentication/#single-sign-on-with-spotify-client-and-a-webview-fallback) )

You should be able to use the token that you receive back to do a refresh when needed though using your existing endpoints.  I haven't implemented anything in this library, but it would probably be a nice enhancement if this library could deal with refreshing tokens. 

Anyways, sorry for the subpar answer earlier in this thread.  Hopefully this helps.  Thanks @divyanshu013 for finding #42 and refreshing my memory.

**Comment by divyanshu013** [comment]
Thanks for confirming 😄

**Comment by cjam** [comment]
Cleaning up old issues, can reopen if needed.
