### ISSUE TITLE
Could not retrieve req.body.code as it is { code: (null) } from tokenSwapURL

### ISSUE THREAD

**Issue by rmtry** [cjam/react-native-spotify-remote#148]
Hi,

I follow the example on iOS (both on React Native project and a server). When I run `const session = await SpotifyAuth.authorize(spotifyConfig)`, it opens Safari and requires login, some confirmation, and then redirects back to the app from `https://server/callback`. At the same time, it also sends a POST /swap to the Server but the `req.body.code` is `(null)`. Therefore, I couldn't get the access token and the authentication process was failed.

What could possibly be wrong in my case? Thanks all.

----
"react-native-spotify-remote": "^0.3.9"
![image](https://user-images.githubusercontent.com/17885445/123633414-d8568000-d821-11eb-91f6-c1385825708e.png)

**Comment by cjam** [comment]
Are you running this on a device that has spotify installed?

**Comment by rmtry** [comment]
Hi,

I was able to fix the problem. Turn out that it needs to be redirected straight from Spotify API, not via a 3rd party server.
On the Spotify API dashboard, I set the callback to be `https://myserver.com/spotify/callback`, which is wrong.

Anyway, thanks for your support!
