### ISSUE TITLE
PlayerStateChanged does not get triggered on pausing, end, start song

### ISSUE THREAD

**Issue by rmtry** [cjam/react-native-spotify-remote#149]
Hi

I want to update the app information from the remote player state, but the event only gets triggered when I used the SpotifyRemote object, not from the device's player itself (iOS). E.g Open the Notifications menu and pause the music from there, but no event got fired and my app still displays as if the track is running.

I tried both with `.addListener()` and `.on()` but same results.
```
    SpotifyRemote.addListener('playerStateChanged', (event) => {
      console.log('playerstatechange', event.isPaused)
      // does not fired when pause from notification
    })

   SpotifyRemote.playUri(item.uri) // triggers `playerStateChanged`
```

"react-native-spotify-remote": "^0.3.9",

**Comment by cjam** [comment]
it appears you're not awaiting the `playUri` promise, please try and await this and let me know if the problem persists.  All of these apis have been developed and tested using the example app in within the repo, so perhaps check there for examples of various apis.

**Comment by cjam** [comment]
Is this still an issue or did awaiting things fix your issue?

**Comment by cjam** [comment]
Going to close this one as it seems like it may have been resolved via the comment.
