### ISSUE TITLE
Implement playItem with skipToTrackIndex

### ISSUE THREAD

**Issue by hspinks** [cjam/react-native-spotify-remote#15]
In the Spotify iOS SDK [v1.0.2 release](https://github.com/spotify/ios-sdk/releases/tag/v1.0.2), Spotify added a new method to SPTAppRemotePlayerAPI to play a playlist from a given index:

[`-(void)playItem:(id<SPTAppRemoteContentItem>)contentItem skipToTrackIndex:(NSInteger) index callback:(nullable SPTAppRemoteCallback)callback`](https://github.com/spotify/ios-sdk/blob/421973e65d9d4279cb37b37ab00821680f407bdf/SpotifyiOS.framework/Versions/A/Headers/SPTAppRemotePlayerAPI.h#L74)

I'm happy to help contribute this functionality to the package! Let me know if there are any specific guidelines I should follow in contributing, or generally if you have any advice for developing a native module for React Native, as I'm fairly new to that.

Really nice work with this package in general, this has been super helpful and easy to work with

**Comment by cjam** [comment]
Hey sorry for the huge delay, I've been traveling around the world for the past 4 months and am getting back into this repo.

My plan is to first get this repo working with CocoaPods and update to the latest SDK.  At that point, I will likely be trying to incorporate the new changes.  

I will keep you posted with contribution help.  I have to get myself back into this repo and remember where this repo is at for.

**Comment by cjam** [comment]
This is now in release v0.1.0
