### ISSUE TITLE
INVALID_APP_ID Android on production with code: 'EUNSPECIFIED'

### ISSUE THREAD

**Issue by minhchinh97h** [cjam/react-native-spotify-remote#154]
Hi,

I am facing an issue when using Spotify Remote on Android production app (iOS and Android dev mode work fine).

The code `const session = await SpotifyAuth.authorize(spotifyConfig)` throws an error of
`
err: {
    nativeStackAndroid: [],
    userInfo: null,
    message: 'INVALID_APP_ID',
    code: 'EUNSPECIFIED',
    line: 28,
    column: 1111,
    sourceURL: 'index.android.bundle'
  }
`

I have the correct package ID and SHA fingerprint set up (the Dev version works perfectly) and my React Native version is 0.63.3. Are there be any extra configurations for production that I should look into?

**Comment by cjam** [comment]
Hmm.. I don't believe so.  I've used this library in production apps without any problem.  So you've got a different Package Id and SHA setup for your production app?

**Comment by minhchinh97h** [comment]
Hi thank you for the reply,

Yes I had different package ID setup for Dev and Prod. However, I changed both to Prod package ID afterwards and added that package ID to my Spotify dashboard but only Dev works.

**Comment by cjam** [comment]
@minhchinh97h did you ever resolve this issue?

**Comment by cjam** [comment]
Housekeeping, haven't heard back from this in a while.
