### ISSUE TITLE
Spotify authentication issue on ios...USA spotify accounts are not working for past 2 days.

### ISSUE THREAD

**Issue by dev-pixarsart** [cjam/react-native-spotify-remote#165]
Hi @cjam !

First of all, just want to say thank you for this amazing library! It is going to help us a lot!

We are using react native module for the Spotify Remote SDK in our app. It was working fine on both android & iOS, but for past two days its not authenticating on iOS for US and Pakistani registered spotify accounts. We have tried Sri-Lanken spotify account, its working.

We are stuck at this problem, all the app is complete. Can you please guide us to resolve this problem?

**Comment by dev-pixarsart** [comment]
Thank you so much for replying @hoangvvo!

We are testing from Pakistan and the Spotify account is also registered in Pakistan. If it is a restriction from Spotify then why it is working on android. We have tried to register an account using VPN but Spotify detects the VPN and we can’t create an account using VPN. And if we login Spotify app with Pakistani account and change the country using VPN it does not work, same for US account. 

Even we have tried with a premium Spotify account registered in US, it does not authenticate. This issue is happening for past two days.  

Right now we are using an account that is actually registered in Sri Lanka, and that is working.

**Comment by cjam** [comment]
Thanks for helping @hoangvvo, sorry for my late reply.  I have not tried to debug or use multiple accounts from multiple geographic locations.  What version of this package are you using?  I released a new pre-release version recently that you may want to try if you haven't.  It uses the latest SDK's from spotify.  You can install it using 
`yarn add react-native-spotify-remote@next`

**Comment by cjam** [comment]
Doesn't seem to be active anymore, cleaning up.
