### ISSUE TITLE
[3.0.11-1] External folders are empty after update

### ISSUE THREAD

**Issue by rpavlovs** [cjam/react-native-spotify-remote#168]
Getting build errors with missing source files on both iOS and Android. 

Upon further look it seems both `*/external` folders are empty. 

Interestingly, while `yarn` is running during update, the contents are there, but then right before it's done they disappear. I'm guessing post–install step removes them and git submodule command fails.

Version: `3.0.11-1`

**Comment by cjam** [comment]
What's weird, is that this should have been fixed by #164 but I just tried to pull it into a test project and it seems the `package.json` is incorrect.  I may try and publish a new pre-release and see if that fixes it.  Not sure why the package.json is incorrect.

**Comment by cjam** [comment]
I think I've fixed this.  Not sure what happened but it seemed that the package.json still had some old scripts, so perhaps I released from the wrong point on master.  Anyways, try and install `@next` and see if things are fixed.

**Comment by rpavlovs** [comment]
Thanks for a quick fix, it worked!
