### ISSUE TITLE
Update docs for Android setup

### ISSUE THREAD

**Issue by cjam** [cjam/react-native-spotify-remote#169]
On android 11 we should specify the connections. Adding this line to AndroidManifest.

`<queries>
    <package android:name="com.spotify.music" />
</queries> 
 `

https://community.spotify.com/t5/Spotify-for-Developers/Why-can-t-I-use-the-SDK-on-Android-OS-11/m-p/5062921/highlight/true#M1438

_Originally posted by @IbrahimCanKALYA in https://github.com/cjam/react-native-spotify-remote/issues/129#issuecomment-960506071_

**Comment by cjam** [comment]
Done as part of some other work

**Comment by lucianobracco-geojam** [comment]
what other work did you do in order to make it work ?@cjam 
I am currently connecting and is not working
