### ISSUE TITLE
canSkipPrevious permission Types are different on iOS and Android

### ISSUE THREAD

**Issue by P-Russell** [cjam/react-native-spotify-remote#171]
Hello.

Thanks again for the work you have put in to this library.

I have noticed a small bug in the permissions type. I have to do this logic to get the canSkipPrevious to work.

```javascript
const canSkipPrevious = Platform.OS === 'ios' ?
      spotifyPlayerState.playbackRestrictions.canSkipPrevious : spotifyPlayerState.playbackRestrictions.canSkipPrev;
```

**Comment by cjam** [comment]
Good find. I'll mark this as a bug for now and take a look at it when I've got some spare time.
