### ISSUE TITLE
Upgrade react-native-events

### ISSUE THREAD

**Issue by IbrahimCanKALYA** [cjam/react-native-spotify-remote#173]
Hi @cjam  react-native-events has dependency events : v1 

events current version is 3.0.0 this dependency different cause build problems with other libraries.
 if react-native-events upgraded 1.0.20 the problem will fixed. 

I tried to upgrade & create PR but example app only work on iphone emulator,  on iphone device debug run it throws error named Spotify.h not found 

Anyway i upgraded the version of react-native-events & i tried on iphone emulator it seem fine, if u have time to look on this , i'll appreciate.

Thanks in advance

**Comment by cjam** [comment]
@IbrahimCanKALYA I just published a new pre-release for this.  It should be available via the `@next` npm tag
