### ISSUE TITLE
App Remote Connection: Protocol Error

### ISSUE THREAD

**Issue by cjam** [cjam/react-native-spotify-remote#2]
For some reason, right now there is an issue where the app will become disconnected from Spotify and can't reconnect due to some protocol issue (will have to follow up with Spotify team with more details about how to reproduce).

Either way, it would be good to be able to get more verbose error messages when it happens.

**Comment by sslash** [comment]
I'm getting this error as well when I do login with the token (just copied the example). Is there a way around it, or are we basically just waiting for the Spotify team to bring more info?

**Comment by cjam** [comment]
The information appears to be in there, however, I'm just not currently propagating out the error messages as it's within some structure.  However, I have found that one of two things generally happens to me while using this package:

1. The auth connection fails because I either forgot to start the auth server or my ip address changed.
2. The remote connection fails with a strange stream protocol type error.  The only way I've found around this one is shutting down the Spotify App and my App and restarting my app.  Hopefully that helps.

**Comment by cjam** [comment]
I've got an update coming for this, double check that you've got your bundle id added in your application settings on spotify dashboard

**Comment by sslash** [comment]
I've reinstalling the project, clear caches, reset simulator etc but it still fails. I'm wondering if it could be something else. I upgraded from the react-native-spotify library to this one, and it used to work fine with that lib.

**Comment by cjam** [comment]
@sslash, I've added an example project which might be useful to take a look at here: https://github.com/cjam/react-native-spotify-remote/tree/master/example

Also more specifically, there are some instructions for setting up the new SDK here:

[Spotify iOS Quickstart](https://developer.spotify.com/documentation/ios/quick-start/#setup-the-ios-sdk) in the ► Configure Info.plist

You need to setup the app to support both opening the Spotify App and your callback URI (which I presume you already have setup).

One more question, what version of iOS are you using this on?

**Comment by sslash** [comment]
Yeah, I've done all of this. `auth.initialize` succeedes with a token, but it fails on `connect`. The error is:
```
AppRemote: Failed connection attempt with error: Error Domain=com.spotify.app-remote.transport Code=-2000 "Stream error." UserInfo={NSLocalizedDescription=Stream error., NSUnderlyingError=0x282b1ebb0 {Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, NSLocalizedRecoverySuggestion=Reconnect the transport to the Spotify app., NSLocalizedFailureReason=A stream error has occured in the transport.}
```
This happens after the app sends me to spotify and it authorizes correctly and sends me back to the app again.

**Comment by sslash** [comment]
Just realised this: if my Spotify app is already open *and* playing a song, and then I run my app, it works. But if the Spotify app is not open, or if its open but it isn't playing a song, and I open my app, the will error happen.

**Comment by cjam** [comment]
Ah Interesting.  Thanks for the feedback.  I haven't been able to figure out when and why this error occurs and have been trying to hone in on how to reliably reproduce it so that I can ask the Spotify team with more details.

I've found that when I run into this error, I usually end up having to quit spotify and my app and then start my app back up.  Once it goes through the auth process it's usually fine.  But it's interesting about the song playing versus not.  

That's great feedback.  I'll try to find some time to take a look into this as it's definitely a blocker for this library being used in a production setting.

**Comment by cjam** [comment]
I've included some of the details from this issue in https://github.com/spotify/ios-sdk/issues/51 in hopes that the Spotify team can shed some light.

**Comment by cjam** [comment]
> Just realised this: if my Spotify app is already open _and_ playing a song, and then I run my app, it works. But if the Spotify app is not open, or if its open but it isn't playing a song, and I open my app, the will error happen.

I have found similar behavior around playing vs not playing.  Sorry I haven't had a chance to look into this as I am quite busy with school these days.  Hopefully I'll find some time for it soon.

**Comment by sslash** [comment]
Thanks for the update @cjam ! Let me know if there's anything I can do to help (if it's on the JS side that is! I'm pretty much a newb when it comes to objective c stuff).

**Comment by cjam** [comment]
I think this issue might be related to iOS backgrounding apps if they aren't playing music or doing anything.  Spotify mentions it in their docs [here](https://github.com/spotify/ios-sdk#frequently-asked-questions)

I will need to solve this for my app, so I'll keep this updated with any progress I make.

**Comment by brunomartinez16** [comment]
Anyone managed to find a solution for this?

**Comment by cjam** [comment]
@brunomartinez16 is it related to the app backgrounding that iOS does?  To determine if its related, try to keep your spotify app open and playing music while your app connects to it.

**Comment by brunomartinez16** [comment]
Yep. For example if I change the device from iPad to the web player I lost the connection so to restore it I had to play a song with authorizeAndPlayUri so the sound is changed again to iPad. I can't find a way of authorizing without playing a song

**Comment by lucasgismondi** [comment]
I have the same issue where Spotify needs to be playing a song for me to connect. Once connected, it works perfectly.

**Comment by brunomartinez16** [comment]
Yeah but try to switch de sound to a device with spotify connect like web player. It will disconnect and when you reconnect the sound will change to the previous device

**Comment by lucasgismondi** [comment]
Ah you're right. But is this an issue because of the background capability or is it a bug with this library in general?

**Comment by cjam** [comment]
I'm doing a bunch of work on this library right now.  Exercising more and more of the edge cases through the example app in the repo.

The backgrounding issue is caused by iOS suspending Spotify, which in turn suspends the messaging server and therefore disconnects the remote.

For my own project, I'd like this library to be as robust as possible, so I'm exploring some of these cases right now.

**Comment by brunomartinez18** [comment]
Hey all! This could be a workaround solution for this if you use iPads https://support.apple.com/en-us/HT207582 
If you keep your app and Spotify opened, then it wont get disconnected.
Is not the better solution but for the short term it could help

**Comment by lucasgismondi** [comment]
@cjam This answer might help with this issue https://github.com/spotify/ios-sdk/issues/51#issuecomment-578376972

In the ios quick start it's saying you can authorizeAndPlayURI. In the comment I linked, Erik mentioned that he just plays a silent track on authorization. I guess a better solution would be to check if you are connected, if so just use the normal playURI function, otherwise use authorizeAndPlayURI. Thoughts?

**Comment by JoshLiquornik** [comment]
Same issue here. Any updates on this?

**Comment by cjam** [comment]
@JoshLiquornik, this issue is caused by iOS backgrounding Spotify (if it isn't playing any music) and therefore the message server (running in Spotify App) is shut down and the connection is severed.  To preserve the connection, Spotify must be playing audio to prevent it from being backgrounded.

I have yet to tackle this one effectively in my application, however, a strategy that I'm considering is playing silence. 

```ts 
const silentTrack = "spotify:track:7p5bQJB4XsZJEEn6Tb7EaL";
```

Not sure if it's a feasible workaround for you, but that's what I'm going to try.

**Comment by lucasgismondi** [comment]
@cjam have you looked into the authorizeAndPlayURI function? Not only is the backgrounding issue a thing after you connect, but also just connecting in the first place. I'm wondering if this function will help in that case. Doesn't seem like it's being used in this library.

**Comment by cjam** [comment]
@lucasgismondi Great idea, I'll try and get that exposed asap.

**Comment by cjam** [comment]
@lucasgismondi This has been implemented in `v0.2.0`.

Described in the docs here: https://cjam.github.io/react-native-spotify-remote/interfaces/spotifyapiconfig.html#playuri

**Comment by lucasgismondi** [comment]
Thank you so much for this update @cjam!!! I will test this tonight and let you know if all is working.

**Comment by lucasgismondi** [comment]
@cjam These are the results from my tests:
1. I am unable to connect to Spotify even if Spotify is active in the background playing a song.
2. I tried using the new playURI parameter in the config but after I initialize, no song plays. If I try to connect, I am unable to.

My config looks something like this:

```
spotifyConfig = {
        clientID: SPOTIFY_CLIENT_ID,
        redirectURL: SPOTIFY_REDIRECT_URL,
        tokenRefreshURL: SPOTIFY_TOKEN_REFRESH_URL,
        tokenSwapURL: SPOTIFY_TOKEN_SWAP_URL,
        playURI: 'spotify:track:6IA8E2Q5ttcpbuahIejO74',
        showDialog: false,
        scope: ApiScope.AppRemoteControlScope, <Other scopes Im using...>
    };
```

The initialize is working just fine and is returning a valid token.

The error I'm receiving is this:
![image](https://user-images.githubusercontent.com/17787783/74894450-04740e00-535d-11ea-9169-c0102b3225bf.png)

The code Im calling is basically:
```
const token = await SpotifyAuth.initialize(this.spotifyConfig);
await SpotifyRemote.connect(token);
```

Is there anything I'm missing here?

**Comment by cjam** [comment]
@lucasgismondi Did you do a `pod install` after upgrading?

**Comment by lucasgismondi** [comment]
Yes I did. Seems to have upgraded successfully
![image](https://user-images.githubusercontent.com/17787783/74897505-4bfe9800-5365-11ea-94a0-4040c2bd8742.png)

**Comment by lucasgismondi** [comment]
Also I'm noticing that with showDialog set to false, the auth dialog still shows.

**Comment by cjam** [comment]
k, I'm going to dig into this on my application and see if I can figure out what's going on for you.

One option is you can throw a breakpoint in the Objective C code to make sure the options are making it.

Two spots I'd place some breakpoints would be:

https://github.com/cjam/react-native-spotify-remote/blob/c9b5bb28c79290c23eb073fe4cf64ca14052bb04/ios/RNSpotifyRemoteAuth.m#L250 

Where you can inspect the values of `_apiConfiguration`, `_sessionManager` and `options`.

On the remote side you can put a couple in:

**app remote disconnected**
https://github.com/cjam/react-native-spotify-remote/blob/c9b5bb28c79290c23eb073fe4cf64ca14052bb04/ios/RNSpotifyRemoteAppRemote.m#L146

**app remote failed to connect**
https://github.com/cjam/react-native-spotify-remote/blob/c9b5bb28c79290c23eb073fe4cf64ca14052bb04/ios/RNSpotifyRemoteAppRemote.m#L152

**app remote established connection**
https://github.com/cjam/react-native-spotify-remote/blob/c9b5bb28c79290c23eb073fe4cf64ca14052bb04/ios/RNSpotifyRemoteAppRemote.m#L156

**Comment by lucasgismondi** [comment]
On the auth side it looks like the correct options are being passed through and the _apiConfiguration is set correctly. I'm not really sure what I should be looking for in _sessionManager but it seems okay also.

On the remote side.. it's hitting didFailConnectionAttemptWithError. accessToken is nil by the time it gets here. Unsure if that is relevant.

Is there anything specific I should be looking for?

**Comment by cjam** [comment]
Hey @lucasgismondi, I integrated it into my project this morning and have been using it without any problems.  Tested it with `playURI` and `showDialog`, both functioning as expected.

hmm... when you set a breakpoint in the didFailConnectionAttemptWithError, try and inspect the error.  You may need to drill into it to get the root cause.

**Comment by lucasgismondi** [comment]
Okay glad it's working for you. I'm obviously doing something wrong on my end. I'll dig into that function a bit more now.

One last question though.. after setting playURI, will the song play after initialization or after connection?

**Comment by cjam** [comment]
Good question.  When I was testing it out in the Example app I found the following behavior:

|`playURI`|Spotify State| Resulting Behavior |
|-|-|-|
|`undefined`|Playing or Paused| Only Authenticates and returns back to your app|
|`""`|Playing|Authenticates and returns back to app (no change to playback)|
|`""`|Not Playing|Authenticates, resumes playback and returns back to app|
|`"someSongId"`|Playing|Authenticates and returns back to app (no change to playback)|
|`"someSongId"`|Not Playing|Authenticates, plays `"someSongId"` and returns back to app|

**Comment by cjam** [comment]
@lucasgismondi have you tried killing spotify and letting your app open it back up?

**Comment by lucasgismondi** [comment]
So that would make sense if it played right after initialization and it would also make sense that I'm still getting a connection error. Others seem to have had this issue and the solution was to delay the connection https://github.com/spotify/ios-sdk/issues/35#issuecomment-452090587. 

However, if I remove the ```SpotifyRemote.connect(token)``` line and just keep the init.. There's no errors but the song doesn't play. Yes I have tried with the app both killed/backgrounded but no luck.

**Comment by lucasgismondi** [comment]
Okay so update. I found this gem in the console ```-canOpenURL: failed for URL: "spotify:" - error: "This app is not allowed to query for scheme spotify"```

To fix this I had to put:
```
<key>LSApplicationQueriesSchemes</key>
  <array>
    <string>spotify</string>
  </array>
```
in my info.plist.

Once I did this and initialized, I was asked to open spotify and I was redirected to spotify and the song began to play!

A couple questions from this:
1. Is this the expected behaviour? If so, is there any way to redirect back to my app once spotify is open and playing? (other than manually doing so)
2. Is this the same behaviour as authorizeAndPlayURI? Are you using authorizeAndPlayURI somewhere?

**Comment by cjam** [comment]
Ah good one, shoot I probably should've mentioned that somewhere.

So this library uses the session manager as it had a more general approach to the authentication portion that the library needed.  To answer your questions:

1.  It will absolutely redirect back to your app, you just need to have a URL handler setup in your app.  For instance in the example app it is setup here:

https://github.com/cjam/react-native-spotify-remote/blob/c9b5bb28c79290c23eb073fe4cf64ca14052bb04/example/ios/example/Info.plist#L26

and in the `.env` file i've got this value:
```env
SPOTIFY_REDIRECT_URL="example://spotify-login-callback"
```

2.  If you pass in `playURI` it will pass it in as an argument to the Session Manager initialze method which has more or less the same effect as using the remote.authorizeAndPlayURI

3. I ran into this as well and exposed a method on the Auth to end the session which can be found here: 

https://cjam.github.io/react-native-spotify-remote/interfaces/spotifyauth.html#endsession

Hope that helps.

**Comment by lucasgismondi** [comment]
1. Thank you that worked!!!
2. Okay perfect
3. Yes saw that right after I asked that question. Thank you

This is working really well now, amazing work <3

**Comment by cjam** [comment]
Alright, so I think I might close this issue, as it seems that there is now a reasonable way to avoid this error.

**Comment by himanshuchugh1999** [comment]
@cjam after changes in info.plist i was able to redirect back to to my app but the songs didn't play on ios deviice but is working on android

**Comment by cjam** [comment]
@himanshuchugh1999 can you try and shut down spotify and try again?

**Comment by himanshuchugh1999** [comment]
still not able to is there any extra things that to be done for ios apart from install the package and pod install and changes in info.plist.
Please help @cjam

**Comment by cjam** [comment]
Did you update your `AppDelegate`?

**Comment by himanshuchugh1999** [comment]
@cjam  i did changes in appdelgate.m 
what is happening is when i click on play button the app takes me to spotify and it shows authorizing and then redirects to my app then it gives error
'Couldn\'t authorize with or connect to Spotify', [Error: The operation couldn’t be completed. (com.spotify.sdk.login error 3.)

The data couldn’t be read because it isn’t in the correct
