### ISSUE TITLE
Can't run the example project on Android

### ISSUE THREAD

**Issue by lorenzozanotto** [cjam/react-native-spotify-remote#45]
Firstly, thank you @cjam and @YozhikM for your work on porting the library to Android 🎉

I'm trying to run the example project on Android and I noticed a few things

1. The SpotifySDK in the `android/externals` folder has no files in it. I had to manually copy and paste the Spotify SDK files inside the folder to silence a compile time error.
2. The JS library specifies the main file in the `package.json` as `dist/index.js`, but the folder does not exists. I had to change the main file to `index.js`
3. After doing that, I get an error saying that the modules exported by the `src/index.ts` file are all undefined as you can see below. 

My `src/index.ts` file looks like this

```js
import Spotify from './src';
export default Spotify;
```

<img width="518" alt="Screenshot 2020-05-17 at 15 35 18" src="https://user-images.githubusercontent.com/4095859/82148380-1a0dac80-9854-11ea-834a-e9def83b7eec.png">

Thanks for all your hard work, I feel like this project is finally coming into a stable release 😃

**Comment by cjam** [comment]
@lorenzozanotto, looks like there are a few things I need to automate.

The Spotify SDK is pulled in as a git submodule, try and run `yarn submodule` or alternatively `git submodule update --init --recursive`.

The project is written in typescript, and as it needs to be compiled.  This can be done with a `yarn build`

Hopefully that helps.

**Comment by lorenzozanotto** [comment]
@cjam that was it! Thanks for the thorough explanation and I'm glad these informations are going to be in the readme. I can consider this issue closed.

**Comment by MrBuggySan** [comment]
@lorenzozanotto @cjam one small question on which package name to use on the Spotify Dashboard?

I've used these three already:
com.example
com.reactlibrary
com.facebook.react

but they give me the same response of:`{"message":"ACCOUNTS_INVALID_APP_ID:INVALID_REQUEST: Invalid app identifier (iOS Bundle ID, Android Key Hash)"}`

**Comment by cjam** [comment]
@MrBuggySan You should be able to find the identifiers within the project, but the ones that I have setup in my own app with spotify.

redirect Url:
example://spotify-login-callback

Bundle Id (iOS):         
org.reactjs.native.rnspotifyremote.example

Android Packages: 
com.react.native.spotify.remote.example 5E:8F:16:06:2E:A3:CD:2C:4A:0D:54:78:76:BA:A6:F3:8C:AB:F6:25

**Comment by MrBuggySan** [comment]
Thanks @cjam ! I'm still getting used to Android :)

**Comment by cjam** [comment]
All good @MrBuggySan me too
