### ISSUE TITLE
Android - getSession returns null before authorize 

### ISSUE THREAD

**Issue by donghee214** [cjam/react-native-spotify-remote#46]
Hi! Huge thanks for the android release for v0.3, looking great so far

Migrated over and updated to the authorize method along with the array representation of scopes. `auth.authorize()` seems to work fine returning a proper session.

On Android `auth.getSession()` seems to always return `null` whenever it's called before the `auth.authorize()` even if it was just recently authorized. On iOS it appears that `auth.getSession()` will still give you the most recent session so long as you've authorized within the past day or so, but on android whenever the app loads you need to authorize before `auth.getSession()` will return a non-null value.

Thank you!

**Comment by cjam** [comment]
ah yes.  Android doesn't have a session manager like iOS does.  But I've actually discovered that android doesn't actually require a token for connecting the remote.  So hopefully an enhancement can be added that will allow connection on android without the authorize.  The idea behind the session, is that you should be able to store it in your app and if it hasn't expired you should be able to still use the token to access Spotify's apis.

Hope that helps.
