### ISSUE TITLE
onSongEnd

### ISSUE THREAD

**Issue by hrutvikpatel** [cjam/react-native-spotify-remote#48]
Is there a way to tell when the song ends? I thought that onPlayerStateChange would tell me something like that. But the closest I can get to is pause.

**Comment by cjam** [comment]
@hrutvikpatel you'll get an onPlayerStateChange event when the new song starts.  So, unfortunately, you don't get one when a song "ends" but you know when songs switch

**Comment by hrutvikpatel** [comment]
Will the onPlayerStateChange event fire when the song's playbackPosition reaches the song's duration? This way I could tell when a song ends. As far as I can tell it doesn't tell me that. hmmm

**Comment by hrutvikpatel** [comment]
Thank you for building this library btw!

**Comment by cjam** [comment]
@hrutvikpatel unfortunately you'll only be notified when a new song starts, not when the current song ends.

There isn't a way to set the playback restrictions, they are just informational and there to help developers enable/disable UI based on what the user is allowed to do.

**Comment by hrutvikpatel** [comment]
So by default if I play a track, will the remote start playing a random track once the song is over?

**Comment by cjam** [comment]
I think it depends on the user's setup.  It will play the next song in the context.  If there is no song in the context, I think it will look at the user settings and see if they want it to try and play similar songs.  You could always set the repeat mode to track and just stop it once it starts playing again.

**Comment by hrutvikpatel** [comment]
okay fair thank you!
