### ISSUE TITLE
SpotifyRemoteAPi disconnects on device sleep, lock ...

### ISSUE THREAD

**Issue by david03g** [cjam/react-native-spotify-remote#51]
When I close my device or it sleeps the remote disconnects. As a result, I can't capture playerstate changes when the user is listening to music in this condition which is the way people typically listen to music. Any help to solve this is greatly appreciated!

**Comment by david03g** [comment]
@cjam

**Comment by cjam** [comment]
Hey @david03g yes. Unfortunately it has to do with iOS and how it handles resources for apps in various states. There are ways of keeping your app “alive” and thus maintaining the connection with Spotify. But they’re unfortunately all pretty hacky.

**Comment by david03g** [comment]
Could you please share them if they keep app "alive" when the device is closed. I am open to using hacky soltuions if thats the only way foward (keeping screen awake to stay alive is a bit too hacky though).                          

Anything you know of that points in right direction is greatly appreacited.  Thanks

**Comment by cjam** [comment]
I seem to recall two ways. One is if your app is playing audio. So perhaps some sort of inaudible tone? Another is if your app uses the location service in the background. There may be more as well

**Comment by david03g** [comment]
Playing silent sound does the trick. I used react-native-sound and set the categroy to allow mixed sounds as to not interfere with the Spotify playback

In addition, you have to enable Backgorund Mode capabilties in Xcode and add the following to the info.plist.

<key>UIBackgroundModes</key>
	    <array>
	  <string>audio</string>
</array>

Really glad it works, I have not done any testing on android yet.

**Comment by cjam** [comment]
Awesome. Glad it worked. Yea I don’t think android has the same strict policies as iOS. Hopefully it works!

**Comment by cjam** [comment]
Just cleaning up some issues so I'm going to close this.
