### ISSUE TITLE
TypeError: null is not an object (Expo)

### ISSUE THREAD

**Issue by TomFevrier** [cjam/react-native-spotify-remote#52]
Hello there!

Sorry for the inconvenience, I am quite new to React Native but this package looks amazing! However, when trying to use this module with my Expo-managed app, I get a `TypeError: null is not an object (evaluating 'react_native_1.NativeModules.RNSpotifyRemoteAuth.authorize')` error.

Any idea of what might go wrong? Is it possible to use this module in an Expo-managed app, and if not how can I use it?

Thank you very much!

**Comment by david03g** [comment]
You would have to eject I assume if there was shot of getting it to work on expo. It's probably best to start with react-native-cli for this module.

**Comment by TomFevrier** [comment]
> You would have to eject I assume if there was shot of getting it to work on expo. It's probably best to start with react-native-cli for this module. 

Any tip on how to easily do that (while still using the Expo app)? I don't feel very comfortable editing native code and my only React Native experience is using the expo-cli...

**Comment by MrBuggySan** [comment]
I don't think you can use this with the managed workflow, instead you have to eject your app and go on the "bare workflow" route

**Comment by cjam** [comment]
@TomFevrier, Expo is a really great project and provides a precompiled native runtime layer which works great if it contains everything that you need at the native layer.  Unfortunately, if you want to use your own native packages (like this one) you'll need to eject.

**Comment by cjam** [comment]
Closing
