### ISSUE TITLE
loginWithSession( options ) enhancement 

### ISSUE THREAD

**Issue by david03g** [cjam/react-native-spotify-remote#53]
Including a loginWithSession(options) to the SpotifyAuth object would be immensely useful in the creation of a login flow that does not require the user to authorize over and over again. 

the options would be:  accessToken , expireTime , refreshToken  and perhaps a few more like tokenRefreshUrl.

**Comment by cjam** [comment]
@david03g I very much agree.  I really want this for my own app as well.  It's just not yet at the top of my priority list. PR's are welcome

**Comment by cjam** [comment]
@david03g I'm going to close this issue as there are a few other issues (#67,#68, #42) that relate to being able to use refresh tokens etc. to authorize without having to use the spotify app -> redirect flow.
