### ISSUE TITLE
is offline playback available here?

### ISSUE THREAD

**Issue by nlaitan** [cjam/react-native-spotify-remote#55]
Hello! 
Thanks for the librarie, I have an intention to use offline player from spotify and I wondered if this library would allow me that. From what I read, I understood that the spotify sdk api allows it and I would like to be sure that I have this feature.

Obviously, this is only a question, not a bug or an request

Regards, Nico

**Comment by cjam** [comment]
This library connects to spotify directly through their Remote SDK which supports offline playback.  However, I have not tested the auth flow offline and I think there may be some work needed to alllow for establishing connections to spotify in an offline case.
