### ISSUE TITLE
Get the loading indicator and reconnects to Spotify when repeatedly calling play

### ISSUE THREAD

**Issue by rohit-ganapathy** [cjam/react-native-spotify-remote#56]
Hey @cjam. First of all thanks for this library. Really handy. So I wanted to know if it is normal to see the loading indicator with android when app is connecting to Spotify. Also when play and pause is called in quick succession, repeatedly, the loading indicator appears.... signifying that it is connecting to Spotify. Is this normal behaviour?

**Comment by cjam** [comment]
The loading indicator is normal when the library is waiting for the auth response from spotify.  Play/Pause in quick succession shouldn't show that loading indicator.  Are you awaiting the promises returned from the play/pause?

**Comment by rohit-ganapathy** [comment]
@cjam figured it out. Silly mistake on my end where I was going through auth again when my getPlayerState function hit the catch block. You can close this issue. Sorry for the inconvenience.
