### ISSUE TITLE
Couldn't authorize with or connect to Spotify Error: null

### ISSUE THREAD

**Issue by aliiqbal436** [cjam/react-native-spotify-remote#61]
![image](https://user-images.githubusercontent.com/36224038/87872888-eecf4700-c9d5-11ea-8465-95561ecba23f.png)

this is the erorr log.
here is my code.
![image](https://user-images.githubusercontent.com/36224038/87872876-d3fcd280-c9d5-11ea-963b-a07e88fd5216.png)

**Comment by aliiqbal436** [comment]
I have test the example app to but getting same error.

**Comment by rananajam1** [comment]
Hey did you fix this?

**Comment by aliiqbal436** [comment]
@rananajam1  Yes. Please make sure that your server is running and spotify app is installed on device.
