### ISSUE TITLE
Login doesn't return success or error

### ISSUE THREAD

**Issue by davidsalib** [cjam/react-native-spotify-remote#64]
When I call login, the spotify authentication page doesn't show and I don't get any errors. 
I do see the log `spotify sign in...`, but nothing after that. 

![image](https://user-images.githubusercontent.com/10209934/88579901-ca4c1e00-d018-11ea-9c51-cfa400aef11b.png)

**Comment by cjam** [comment]
Is this in iOS or android?

If in iOS, can you confirm that you've done all of the spotify setup steps outlined on this page: https://developer.spotify.com/documentation/ios/quick-start/

**Comment by cjam** [comment]
I think there should be more verbose errors now as a result of a recent release. Closing for now but can be reopened if needed.
