### ISSUE TITLE
authorize does not return refresh token.

### ISSUE THREAD

**Issue by uptotec** [cjam/react-native-spotify-remote#67]
I have a problem when I used the authorize method in the code below i get a session without a refresh token. the authorize method doesn't use the Authorization Code Flow as I don't receive any requests on the swap endpoint in the backend server, but it uses the Implicit Grant and I need a long term access as my app should do stuff in the background periodically. I don't know if I do something wrong but I tested my backend server and it works and it matches the one on the server-example.

I tested it only in Android and I tested the Spotify app authorize and the web authorize and I did't get a refresh token from both. 

## authorization code
```javascript
const spotifyConfig: ApiConfig = {
  clientID: Clint_ID,
  redirectURL: 'spoticount://redirect',
  tokenRefreshURL: 'http://192.168.1.18:3000/refresh',
  tokenSwapURL: 'http://192.168.1.18:3000/swap',
  scopes: [
    ApiScope.AppRemoteControlScope,
    ApiScope.UserReadRecentlyPlayedScope,
    ApiScope.UserTopReadScope,
    ApiScope.UserReadPrivateScope,
  ],
};

const authorize = async () => {
  try {
    const session = await SpotifyAuth.authorize(spotifyConfig);
    console.log(session);
  } catch (err) {
    console.error("Couldn't authorize with or connect to Spotify", err);
  }
}
```

## the console log
```
{
"accessToken": "BQD9QOU7D9nTRWRCiwUy-aXC5IL6uPpkuq0bJHqeN81Se-WGYb7z1Xs1gml0EuJ__0b-7z00l8WcKTepb_ZNFLD4t8ZRDPgMKWwW0aMxSqeI8u4Cdsso0Kt5FsbqVPmMyygT1-O7koCe-Y7WDxIZgn0M6zeXfKKBR526RDM_LbJRP_djy5LyIRkz9SogII6zO1F31qieRtTK1mNIJrHRUjvghfs",
"expirationDate":"java.util.GregorianCalendar[time=1596071042581,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=libcore.util.ZoneInfo[id=\"Africa/Cairo\",mRawOffset=7200000,mEarliestRawOffset=7200000,mUseDst=false,mDstSavings=0,transitions=126],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2020,MONTH=6,WEEK_OF_YEAR=31,WEEK_OF_MONTH=5,DAY_OF_MONTH=30,DAY_OF_YEAR=212,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=5,AM_PM=0,HOUR=3,HOUR_OF_DAY=3,MINUTE=4,SECOND=2,MILLISECOND=581,ZONE_OFFSET=7200000,DST_OFFSET=0]", 
"expired": false
}
```

## swap endpoint function

```javascript
import { Request, Response } from 'express';
import axios from 'axios';
import { stringify } from 'querystring';
import { encode } from 'base-64';

/**
 * * getAccessToken used to get a token for the Clint app
 * @param code the authorization_code sent by the Clint app
 */

export const getAccessToken = async (req: Request, res: Response) => {
  const { code } = req.body;
  console.log(code);

  // * build the request object
  const reqData = {
    code,
    redirect_uri: process.env.REDIRECT_URL,
    grant_type: 'authorization_code',
  };

  // * set the reqest header
  const reqConfig = {
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      Authorization = `Basic ${encode(
          `${process.env.Clint_ID}:${process.env.Clint_SECRET}`
        )}`;
    },
  };

  try {
    // * sending the reqest and forwarding it to the clint
    const spotiRes = await axios.post(
      process.env.GET_TOKEN_URL!,
      stringify(reqData),
      reqConfig
    );

    res
      .status(200)
      .json({ message: 'ok', ...spotiRes.data });
  } catch (err) {
    // ! sending the error message to the clint app
    console.log(err);
    res.status(err.response.status).json({ message: err.message });
  }
};
```

**Comment by uptotec** [comment]
I made a workaround to solve this issue and I made a pull request to suggest a future solution for it. thanks for this great package. 😀

**Comment by rohit-ganapathy** [comment]
hey @uptotec would love to know what the workaround is! I'm struggling with the same issue

**Comment by uptotec** [comment]
@rohit-ganapathy apply the changes [here](https://github.com/cjam/react-native-spotify-remote/pull/68) this will return you an authorization code not an access token. then you can send this code to your server **the swap endpoint** and use the access token returned to connect the remote. I use this util function to swap and refresh tokens
```typescript
import axios from 'axios';

const Base_Url = 'http://192.168.1.18:3000';

export default async function sendJsonData(url: string, reqData: object) {
  try {
    const res = await axios.post(`${Base_Url}${url}`, reqData, {
      headers: {
        'Content-Type': 'application/json',
      },
      timeout: 8000,
    });
    return res.data;
  } catch (err) {
    return null;
  }
}
```

**Comment by rohit-ganapathy** [comment]
hey @uptotec I tried your fixes and I'm getting quite a few syntax errors during build on the JAVA front. Could you help me out with it? Thanks!

**Comment by cjam** [comment]
@uptotec Thanks again for the PR.  I've been swamped with work and still haven't had a chance to get to it. Apologies.

**Comment by cjam** [comment]
Hey @uptotec.  I don't have a ton of experience with the refresh token flow but would love to get the code from #68 into this library.  I know that in the iOS side, the session returned from the SessionManager has a `refreshToken` (have a look [here](https://spotify.github.io/ios-sdk/html/Classes/SPTSession.html#//api/name/refreshToken)) it seems like the CODE in the android side is similar?  

It hasn't seemed feasible to spend time trying to write integration/unit tests for this package (since Spotify needs to be installed on a physical device), So I've been using the example app in the repo to test all new functionality.  I would love to get some code that could exercise the refresh token flow, not only to serve as an example but also to make sure that the code is working across iOS and Android.  I imagine it would live somewhere in:

https://github.com/cjam/react-native-spotify-remote/blob/c0a81d7fb4dae4686b713268aa51471188729562/example/AppContext.tsx#L121-L139

Any thoughts?

**Comment by uptotec** [comment]
I see your point. In the android Auth flow you have tow options the token option is to get a one-hour token and this flow made for one time login. the other flow is the code option which give you a one-time use code to use it with the swap endpoint and what returned for the swap endpoint is a one-our token and a refresh token.
I have an idea to implement the refresh token bath on android and keep the same code base to work with both android and ios, but first and I need to know in ios when you get the refresh token does the library auto refresh it when it expires or the developer should implement a way to send a request to the refresh endpoint. sorry I don't have any ios device in hand to test this.
when you reply I will try to implement my idea in #68

**Comment by cjam** [comment]
Good question.  It appears that if there is a valid session present, that you can use the SessionManager to renew/refresh the token: 

https://spotify.github.io/ios-sdk/html/Classes/SPTSessionManager.html#//api/name/renewSession

Right now, I'm sending all of the session details over the bridge to the javascript engine.  I'm not sure if I could set the session in iOS or if it is completely managed by the session manager (i.e. need to let it go through the flow).

**Comment by uptotec** [comment]
my Idea is to preform an OS check and if it's android we take the code auth flow and Implement a method to send a request to the swap endpoint and return the response of this call which is the same [SpotifySession](https://cjam.github.io/react-native-spotify-remote/interfaces/spotifysession.html) interface as a resolve for the [authorize method](https://cjam.github.io/react-native-spotify-remote/interfaces/spotifyauth.html#authorize)

now both android and ios have a refresh token returned from  [authorize method](https://cjam.github.io/react-native-spotify-remote/interfaces/spotifyauth.html#authorize) 

about how to use the refresh token I didn't understand if the session manager in ios refreshes tokens or not but to keep one implementation for both OS's I suggest changing the get session method to not just get the session from the session manager in the sdk to the javascript engine. but we can make it send a request to the refresh endpoint with the refresh token that we have already and the response of the request will be what returned from the getSession method and if any thing is happens will return undefined in which case with require reauthorize with [authorize method](https://cjam.github.io/react-native-spotify-remote/interfaces/spotifyauth.html#authorize). so if we implemented this we will achieve a unified solution that works with android and ios.

p.s I implemented similar idea in my app and I works I just use the [authorize method](https://cjam.github.io/react-native-spotify-remote/interfaces/spotifyauth.html#authorize) to get the code and rend request to the swap endpoint and use the returned token to connect the sdk with [connect method](https://cjam.github.io/react-native-spotify-remote/interfaces/spotifyremoteapi.html#connect) and every time I need the session after one hour I send a request to the refresh endpoint and reconnect again and I works fine with android with me.

If you approve this Idea I will implement it in #68 in the library and the example app you will just need to apply the changes made in the library to the library files in the node_modules in the example app

**Comment by cjam** [comment]
hey @uptotec,  I've been thinking about this one a little bit and had an idea to run by you.  It seems that on the iOS side of things, there is a SessionManager abstraction that provides a mechanism to refresh sessions using refresh tokens and URLs if they exist.  This functionality isn't surfaced through the API since Android doesn't have the same concept, but perhaps if a SessionManager was created in the Android side that had a similar interface to the one present in the iOS Spotify Library then a common token/refresh mechanism could be exposed through to the javascript / react side. 

One advantage is that we wouldn't need to do a platform check and we could leverage the native implementation for iOS while providing a similar implementation for Android.  Just some thoughts.

**Comment by cjam** [comment]
@uptotec I finally got the work from your PR merged in for the Android work.  Hopefully you now have a solution to this with version `v0.3.6`
