### ISSUE TITLE
"_OBJC_CLASS_$_RNSpotifyRemoteAuth", referenced

### ISSUE THREAD

**Issue by iMJumpmxn** [cjam/react-native-spotify-remote#7]
Hey,
first of all, thank you for implementing the new Spotify SDK.

After i linked the framework and modified the AppDelegate.m i get this error in xcode: 

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNSpotifyRemoteAuth", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64

**Comment by iMJumpmxn** [comment]
Fixed it

**Comment by cjam** [comment]
Yea I'm currently creating an example project for this.  Also including some better documentation on adding the settings in the right spots.  Glad you figured it out.
