### ISSUE TITLE
IOS: I want to pause the player on ios app terminate.

### ISSUE THREAD

**Issue by aliiqbal436** [cjam/react-native-spotify-remote#73]
Hey, I want to pause the player on ios app termination. I am using `(void)applicationWillTerminate:(UIApplication *)application` this delegate method to detect the termination But how i can call the pause method in it.

**Comment by cjam** [comment]
Each of the module classes in this package should have a singleton static instance.  So I think you should be able to access it like this from iOS:

```objective-c
  [[RNSpotifyRemoteAppRemote sharedInstance] pause:^(id result) {
    // success
  } reject:^(int *code, int *message, int *error) {
    // error
  }];
```

**Comment by aliiqbal436** [comment]
@cjam Thanks.
