### ISSUE TITLE
SpotifyIos.h not found on Xcode

### ISSUE THREAD

**Issue by DimarDM** [cjam/react-native-spotify-remote#78]
im trying to run the example app and i have setup everything but when i try to build it it fails.
Error: SpotifyIos.h not found

**Comment by cjam** [comment]
It sounds like you may be missing the submodule with the library code in it.  In the project root can you try and run

`yarn submodules` or `npm run submodules`

**Comment by cjam** [comment]
Just closing as I haven't heard anything further
