### ISSUE TITLE
In Release mode there are UENSPECIFIED error.

### ISSUE THREAD

**Issue by halilbakilan** [cjam/react-native-spotify-remote#79]
My app is working debug mode. But release apk is not working. It is authorize error.

![8fc85de2-8f6e-4f22-984a-df6d86f9589b](https://user-images.githubusercontent.com/28761969/96367753-7012b300-1158-11eb-9076-0a484afcaec3.jpg)

**Comment by cjam** [comment]
Looks like an invalid app Id.  I seem to recall having to put the keystore fingerprint into Spotify's app registration in their dev console.  But I haven't been in the android project for a while.

**Comment by halilbakilan** [comment]
I were get sha1 for release apk and I use this sha1.
