### ISSUE TITLE
Unable to install with React Native 0.63.3 using NPM

### ISSUE THREAD

**Issue by djwillcaine** [cjam/react-native-spotify-remote#80]
# Steps to reproduce

```
npx react-native init Test
cd Test
npm i --save react-native-spotify-remote
```

# Result

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: Test@0.0.1
npm ERR! Found: react-native@0.63.3
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.63.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.61.5" from react-native-spotify-remote@0.3.2
npm ERR! node_modules/react-native-spotify-remote
npm ERR!   react-native-spotify-remote@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by djwillcaine** [comment]
Seems like this might be an issue with npm? Installing with yarn seems to work but does throw up some warnings about dependencies too.

**Comment by cjam** [comment]
Hmm good catch, I'll likely have to look at the peer dependency to make it compatible with new versions.

**Comment by ngocketit** [comment]
Same issue, any update on this @cjam. Thanks!

**Comment by cjam** [comment]
Sorry @ngocketit I've been heads down with work trying to hit a couple deadlines, so I won't be able to get to this for a little bit

**Comment by cjam** [comment]
I just need to update the peerDependency in the `package.json` to >=0.60 instead of ~0.61.5.  Hopefully I can squeak this in and some other small enhancements soon!
