### ISSUE TITLE
SpotifyRemote.connect() fails without error message if Spotify is not installed (Android)

### ISSUE THREAD

**Issue by djwillcaine** [cjam/react-native-spotify-remote#81]
Any call to the `SpotifyRemote.connect()` function results in a rejected promise that returns `[Error: null]`. Tested using the example app, and confirmed it is still an issue.

As mentioned [here](https://github.com/cjam/react-native-spotify-remote/blob/master/example/Components/ConnectButton.tsx#L12-L17) I thought maybe this could be fixed by re-authing the user, but the result is no different the second time. Currently my app is stuck in a loop of trying to auth the user over and over.

I wondered if perhaps the access token granted didn't have the correct scope but I can't think of a good way to test this theory without putting together an entire native app. I don't think there's anyway to test if we have 'app-remote-control' using their web API console.

**Comment by djwillcaine** [comment]
OK this one was a somewhat silly mistake on my behalf.

The Spotify SDK requires the target device already has Spotify installed. By running this on my phone with Spotify installed (as opposed to the blank android emulator) the problem is solved!

Perhaps we could do with some more helpful error messages, though. In the event that `SpotifyRemote.connect()` fails, it would be very useful to know if this is because the user has not yet installed Spotify (so we can prompt them to do so).

**Comment by cjam** [comment]
Good idea, there are some hooks in the spotify SDK to check if spotify is installed on the device.  Will just need to surface them through this package.  But yea, better error messages would be good 👍

**Comment by djwillcaine** [comment]
Can also use [react-native-check-app-install](https://github.com/redpandatronicsuk/react-native-check-app-install) as a temporary solution.
