### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by yannikw23** [cjam/react-native-spotify-remote#84]
Hi @cjam! I just started testing this library as I plan to use it for a project. Thanks a lot for creating this library!

I could see myself contributing to this over time. Just wanted to start that by updating the example README to prevent a "gotcha" I spent some time with, but I don't seem to have the necessary rights to create a branch...Would be great if you could grant me the permissions.

Best,
Yannik

**Comment by cjam** [comment]
Hey @yannikw23 ,

Great to hear you're keen to help.  I've added you as a contributor to the repo which will let you make branches.  Another way is to fork the repo and issue a PR back which is how others have contributed in the past.  Anyways, thanks for the help!

Coter

**Comment by yannikw23** [comment]
Thanks! I'm excited to work on this repo as I need it for a crucial feature in my other project. 🎉
