### ISSUE TITLE
Any way to get state change details

### ISSUE THREAD

**Issue by kush-daga** [cjam/react-native-spotify-remote#89]
Currently when we are working with the playerStateChanged event, It returns back the current state of the user, is there any way to get what changes were done in the previous state?

For example: 
I want to trigger a function only when I change the track on my spotify app and not when I seek or maybe pause the song, anyway to implement this other than manually storing the previous state and comparing it with the new state and then updating the state?

**Comment by cjam** [comment]
As the goal of this library is to be a very general wrapper around the functionality that Spotify exposes, the api's provided by this library will continue to mirror those of Spotify's.  There are other options for doing what you are attempting to do.  For instance I generally use https://rxjs-dev.firebaseapp.com/guide/overview for stuff like this.  I'm actually doing something in a project right now that sounds very similar to what you're hoping to do.  In your case it would look something like this:

```ts

// Observable of player state 
const playerState$ = fromEventPattern<RemotePlayerState>(
        (h) => spotifyRemote.addListener("playerStateChanged", h as any),
        (h) => spotifyRemote.removeListener("playerStateChanged", h as any)
      );

// Observable of track changes using Pairwise to do comparison
const trackChanged$ = playerState$.pipe(
  pairwise(),
  filter(([first, second])=>{
     return first.track.uri !== second.track.uri
  }),
  map(([first,second])=>second)  // Map back into the latest event
);

// Alternate approach using distinctUntilChanged

const distinctTrackChanged$ = playerState$.pipe(
  distinctUntilChanged((x,y)=>x.track.uri !== y.track.uri)
);


// Later on in your code you'd subscribe to the observable (either one)

distinctTrackChanged$.subscribe({
  next: (playerState)=>{
    console.log("Song Changed",playerState)
  },
  error:(err)=>console.log("Something happened",err),
  complete: ()=>console.log("Stream complete")
});

```

**Comment by cjam** [comment]
I'm going to close this since this likely won't be added to this library at this point.  Perhaps in the future if spotify changes its apis.

**Comment by kush-daga** [comment]
Awesome, thanks!
