### ISSUE TITLE
Auth window doesnt close

### ISSUE THREAD

**Issue by iMJumpmxn** [cjam/react-native-spotify-remote#9]
After i logged in to Spotify the window shows the Auth token but the doesnt close.

**Comment by cjam** [comment]
It sounds like you're redirect URI isn't being called.  You have registered a callback uri with spotify and added the URL to your app?

**Comment by iMJumpmxn** [comment]
I think the redirect URI  is called cause the safari window shows the access token Or maybe I'm wrong?

I registered the callback url at spotify and defined it at the spotifyConfig in my app

**Comment by cjam** [comment]
You'll also need to have the same callback URI setup in your app's plist.  Take a look at https://developer.spotify.com/documentation/ios/quick-start/#configure-info-plist

**Comment by cjam** [comment]
Closing this one due to lack of activity.
