### ISSUE TITLE
Execution failed for task ':react-native-spotify-remote:bundleReleaseAar' when running assembleRelease

### ISSUE THREAD

**Issue by diegoareval** [cjam/react-native-spotify-remote#90]
Hello there!

Whenever I try to generate a release of my app (using ./gradlew assembleRelease), I get the following error:

> Task :react-native-spotify-remote:bundleReleaseAar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-spotify-remote:bundleReleaseAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-spotify-remote project caused this error: /Users/user/Desktop/projects/coco/movil/cocolanguagemobile/node_modules/react-native-spotify-remote/android/external/SpotifySDK/auth-lib/spotify-auth-release-1.2.1.aar, /Users/user/Desktop/projects/coco/movil/cocolanguagemobile/node_modules/react-native-spotify-remote/android/external/SpotifySDK/app-remote-lib/spotify-app-remote-release-0.7.0.aar

Any idea of what is wrong? Thank you very much!

**Comment by apperside** [comment]
Have you found a solution? I am having the same issue

**Comment by diegoareval** [comment]
No yet bro, I need to set my mind on this but I have this issue. I can't
fix it

**Comment by brobin002** [comment]
Hi! I resolved this issue with  `./gradlew :app:assembleRelease` instead of `./gradlew assembleRelease`! Hope it helps!!

**Comment by diegoareval** [comment]
Awesome, thanks ever so much! I will try to run this command, thanks

**Comment by cjam** [comment]
> Hi! I resolved this issue with  `./gradlew :app:assembleRelease` instead of `./gradlew assembleRelease`! Hope it helps!!

That would absolutely make sense. Great work!

**Comment by diegoareval** [comment]
I made it. The solution, thanks ever so much broo... Thanks

**Comment by cjam** [comment]
I'm going to close this as it seems @brobin002 found a solution to the problem.

**Comment by diegoareval** [comment]
Great

**Comment by diegoareval** [comment]
Other solution is use Android studio to generate a signed build.

**Comment by architect-aimonkey** [comment]
not working for me. Same exact problem

**Comment by andersonaddo** [comment]
`./gradlew :app:assembleRelease` doesn't work for me.

@cjam you mentioned in #90 that you were able to build and release; was that from the `/example` app? You mentioned you did it in Android Studio, but I wonder if you have tried from the cli using `app:assembleRelease`. I ask because I wonder if this is a gradle version issue.

The example [uses a pretty old version of gradle](https://github.com/cjam/react-native-spotify-remote/blob/5a4b4aee407b6239638775e2155842f5be48f2af/example/android/build.gradle#L15), newer RN apps that are created now use 7+

May investigate myself if time permits
