### ISSUE TITLE
2 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by IbrahimCanKALYA** [cjam/react-native-spotify-remote#94]
When i want integrate both sdk's to my app get ann error that named 

/Products/Debug-iphonesimulator/RNSpotify/libRNSpotify.a(RNSpotifyConvert.o)
Products/Debug-iphonesimulator/RNSpotifyRemote/libRNSpotifyRemote.a(RNSpotifyConvert.o)
2 duplicate symbols for architecture x86_64

i need to integrate this sdk 
https://github.com/lufinkey/react-native-spotify
to my application & i think this issue caused by two libs has the same class name.

**Comment by IbrahimCanKALYA** [comment]
Renaming  RNSpotifyConvert to RNSpotifyRemoteConvert solved the issue.

is there any chance to change name of RNSpotifyConvert on base repo ? @cjam 

thank in advance

**Comment by cjam** [comment]
Ah yea that would create some problems. I'll make this into a buy and hopefully it can get done soonish. You can also do a PR for it if you want.

**Comment by IbrahimCanKALYA** [comment]
@cjam thanks for quick reply i created a new PR!

**Comment by cjam** [comment]
Should be fixed in 0.3.4
