### ISSUE TITLE
IOS - playmusic ERROR - Spotify does not appear to be installed

### ISSUE THREAD

**Issue by ricardoaraujojr** [cjam/react-native-spotify-remote#97]
I authenticate and then I call "connect", but it generates the mentioned error. When it is IOS it is obliging to have Spotify open and be playing a song, otherwise it generates this error.

For IOS if you were with Spotify closed shouldn't you open and play the song after connect and playURI, without generating this error?

Code used :

  const session = await SpotifyAuth.authorize(spotifyConfig);   
    await SpotifyRemote.connect(session.accessToken);
   <--- THIS GENERATED ERROR : Spotify does not appear to be installed ---> IF SPOTIFY CLOSED OR SPOTIFY OPENED BUT WITHOUT PLAYED 
    await SpotifyRemote.playUri("spotify:track:6IA8E2Q5ttcpbuahIejO74"); 

Thanks!

**Comment by cjam** [comment]
Hmm.  It sounds like I may have introduced bug in a recent PR to address some issues people were experiencing with errors being too vague.  I'll take a look and maybe just remove the check that I added.  

To confirm, you have spotify installed on the iOS device that this is happening on?

**Comment by cjam** [comment]
Should be fixed in 0.3.4.  The code now uses the method exposed by the Spotify iOS SDK for determining if spotify is installed and gives a better error message if it fails.
