### ISSUE TITLE
Spotify Remote On Google Play

### ISSUE THREAD

**Issue by ricardoaraujojr** [cjam/react-native-spotify-remote#99]
Hi!

When i use this library without publish on google play then works great.
When i use this library after publish on google play then tries to open spotify, shows icon loading ,but does not open spotify.

Is There a problem after publish on google play?

Version package 0.3.3

Thanks

**Comment by ricardoaraujojr** [comment]
This feature doesnt work on publish google play 
await SpotifyRemote.connect(token);
await SpotifyRemote.playUri(spotify:track:3udE6tEHfnlEAb7pbscARK);     

This open a loading from spotify but after doesnt open spotify playing a song

**Comment by cjam** [comment]
It might have to do with your URI handling.  Have you taken a look at the example app?  I have built an app that is in both app stores that is using this library and I recall having to adjust some settings in the android manifest and making sure the intents were setup correctly.  Perhaps double check the documentation on setting up the Spotify android sdk, specifically the setup in the manifest XML etc.
